Improved error/usage messages.

diff --git a/bin/keychain b/bin/keychain
--- a/bin/keychain
+++ b/bin/keychain
@@ -17,7 +17,7 @@ HERE
 }
 
 env="$HOME/.ssh/environment-$HOST"
-options=$(getopt -o he: -l help,env: -- "$@") || usage 1
+options=$(getopt -o he: -l help,env: -- "$@") || usage >&2 1
 
 eval set -- $options
 while [[ $# -gt 0 ]]; do
@@ -26,7 +26,7 @@ while [[ $# -gt 0 ]]; do
     -e|--env)  env="$2" ;;
 
     --) shift; break    ;;
-    -*) echo >&2 "$0: error - unrecognized option $1"; usage 1 ;;
+    -*) echo >&2 "$0: error - unrecognized option $1"; usage >&2 1 ;;
   esac
   shift
 done
@@ -62,6 +62,6 @@ case "$1" in
     fi
     ;;
   *)
-    echo 2&>1 "$0: error - invalid command $1"; usage 1
+    echo >&2 "$0: error - invalid command $1"; usage >&2 1
     ;;
 esac
